# Generated by Django 5.0.4 on 2024-04-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('tail_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('pilot_name', models.CharField(blank=True, max_length=200)),
                ('economy_seats', models.PositiveSmallIntegerField(default=0)),
                ('business_seats', models.PositiveSmallIntegerField(default=0)),
                ('first_seats', models.PositiveSmallIntegerField(default=0)),
                ('arrival_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_arrival_airport_set', to='flights.airport')),
                ('departure_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_departure_airport_set', to='flights.airport')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.plane')),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.planetype'),
        ),
    ]
