# Generated by Django 5.0.4 on 2024-04-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('iata_code',)},
        ),
        migrations.AlterModelOptions(
            name='planetype',
            options={'ordering': ('iata_code',)},
        ),
    ]
